//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVFSModeling.Core.Tests {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVFSModeling.Core.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 44,767489;1175000;100
        ///44,776023;975000;86
        ///44,784046;975000;42
        ///44,792230;975000;17
        ///44,800488;1666000;38
        ///44,808170;1666000;19
        ///44,816201;975000;26
        ///44,825771;975000;32
        ///44,833801;975000;33
        ///44,844056;975000;25
        ///44,852072;975000;67
        ///44,860205;975000;100
        ///44,872129;975000;58
        ///44,878716;975000;100
        ///44,887455;1800000;100
        ///44,896138;1800000;100
        ///44,904030;1866000;100
        ///44,912211;1866000;100
        ///44,920344;1866000;100
        ///44,930581;2000000;100
        ///44,938959;2000000;100
        ///44,946968;2000000;100
        ///44,955724;2000000;100
        ///44,96 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string camera {
            get {
                return ResourceManager.GetString("camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 52,564099;875000;100
        ///52,571991;875000;81
        ///52,580033;1618000;19
        ///52,588037;1618000;29
        ///52,596182;1275000;28
        ///52,604301;1275000;68
        ///52,607634;1275000;100
        ///52,616085;1275000;30
        ///52,624035;1075000;52
        ///52,632164;1075000;77
        ///52,641563;1500000;75
        ///52,651201;1500000;100
        ///52,659644;1733000;100
        ///52,668099;1733000;100
        ///52,676149;1733000;100
        ///52,684018;2000000;100
        ///52,687588;2000000;100
        ///52,695702;2000000;100
        ///52,704143;2000000;100
        ///52,712112;2000000;100
        ///52,720134;2000000;100
        ///52,728075;2000000;100
        ///52,731835;2000000 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string flappy {
            get {
                return ResourceManager.GetString("flappy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 46,566127;875000;100
        ///46,574090;875000;84
        ///46,582192;1175000;10
        ///46,590245;1175000;56
        ///46,598372;1175000;36
        ///46,606412;1375000;46
        ///46,614409;1375000;98
        ///46,627677;1275000;60
        ///46,632184;1275000;100
        ///46,640297;1275000;95
        ///46,648637;1933000;90
        ///46,657164;1933000;100
        ///46,665682;1933000;91
        ///46,674056;1933000;100
        ///46,682194;1933000;91
        ///46,690239;2000000;99
        ///46,698196;2000000;100
        ///46,706298;1866000;100
        ///46,714360;1866000;100
        ///46,722492;1866000;100
        ///46,732870;1866000;75
        ///46,742319;1866000;100
        ///46,750291;1933000;100 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string flappy_new {
            get {
                return ResourceManager.GetString("flappy_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 46,611036;1796000;100
        ///46,622172;1923000;100
        ///46,630161;1923000;100
        ///46,638185;1923000;100
        ///46,650179;2050000;100
        ///46,658191;2050000;100
        ///46,666608;2050000;100
        ///46,678183;2050000;100
        ///46,686199;2050000;100
        ///46,694215;2050000;100
        ///46,702243;2050000;100
        ///46,714240;2050000;100
        ///46,726228;2050000;100
        ///46,734190;2050000;100
        ///46,742249;2050000;100
        ///46,754360;2050000;100
        ///46,762230;2050000;100
        ///46,774281;2050000;100
        ///46,786234;2050000;100
        ///46,794252;2050000;100
        ///46,802251;2050000;100
        ///46,814252;2050000;100
        ///46,828 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string flappy_new_high {
            get {
                return ResourceManager.GetString("flappy_new_high", resourceCulture);
            }
        }
    }
}
